#1. ALS

In [24]:
import numpy as np

land_svd2 = np.array([[1.00,  0.91,  1.00,  1.00,  0.85, -0.85, -0.85, -0.85, -0.81],
[0.91,  1.00,  0.91,  0.88,  0.99, -0.56, -0.56, -0.56, -0.50],
[1.00,  0.91,  1.00,  1.00,  0.85, -0.85, -0.85, -0.85, -0.81],
[1.00,  0.88,  1.00,  1.00,  0.81, -0.88, -0.88, -0.88, -0.84],
[0.85,  0.99,  0.85,  0.81,  1.00, -0.45, -0.44, -0.44, -0.37],
[-0.85, -0.56, -0.85, -0.88, -0.45,  1.00,  1.00,  1.00,  1.00],
[-0.85, -0.56, -0.85, -0.88, -0.44,  1.00,  1.00,  1.00,  1.00],
[-0.85, -0.56, -0.85, -0.88, -0.44,  1.00,  1.00,  1.00,  1.00],
[-0.81, -0.50, -0.81, -0.84, -0.37,  1.00,  1.00, 1.00,  1.00]])

land_svd3 = np.array([[1.00,  0.13,  1.00,  0.96, -0.19, -0.50, -0.53, -0.55, -0.68],
[0.13,  1.00,  0.21, -0.14,  0.95, -0.66, -0.63, -0.61, -0.40],
[1.00,  0.21,  1.00,  0.94, -0.10, -0.56, -0.59, -0.60, -0.71],
[0.96, -0.14,  0.94,  1.00, -0.44, -0.31, -0.35, -0.37, -0.55],
[-0.19,  0.95, -0.10, -0.44,  1.00, -0.54, -0.51, -0.48, -0.23],
[-0.50, -0.66, -0.56, -0.31, -0.54,  1.00,  1.00,  1.00,  0.94],
[-0.53, -0.63, -0.59, -0.35, -0.51,  1.00,  1.00,  1.00,  0.96],
[-0.55, -0.61, -0.60, -0.37, -0.48,  1.00,  1.00,  1.00,  0.96],
[-0.68, -0.40, -0.71, -0.55, -0.23,  0.94,  0.96,  0.96,  1.00]])

mat = np.loadtxt("landauer.matrix")
print(mat)

[[1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 2. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1.]]


In [25]:
def ALS(matrix, l_dim, max_iter=100, tolerance=1e-4):
  m, n = matrix.shape
  P = np.zeros((m, l_dim))
  Q = np.random.rand(l_dim, n)

  iter = 0
  dist = float("+inf")
  while iter < max_iter and dist > tolerance:
    iter += 1

    #Estimation de P
    old_P = P.copy()
    P = matrix @ Q.T @ np.linalg.inv(Q @ Q.T)

    #Estimation de Q
    old_Q = Q.copy()
    Q =  np.linalg.inv(P.T @ P) @ P.T @ matrix

    dist = np.linalg.norm(P - old_P) + np.linalg.norm(Q - old_Q)
  
  print("Number of iterations :", iter)
  return P, Q

In [33]:
P2, Q2 = ALS(mat, 2)
print("Produit des matrices résultantes :")
print(np.round(P2 @ Q2 ,2))
print('\n\n',"Corrélations obtenues avec les matrices ALS :")
print(np.round(np.corrcoef(P2 @ Q2, rowvar = False), 2))
print('\n',"Corrélations obtenues avec la démo SVD de Landauer :")
print(land_svd2)

Number of iterations : 57
Produit des matrices résultantes :
[[ 0.16  0.4   0.38  0.47  0.18 -0.05 -0.12 -0.16 -0.09]
 [ 0.14  0.37  0.33  0.4   0.16 -0.03 -0.07 -0.1  -0.04]
 [ 0.15  0.5   0.36  0.41  0.24  0.02  0.06  0.09  0.12]
 [ 0.26  0.84  0.61  0.7   0.39  0.03  0.08  0.12  0.19]
 [ 0.45  1.23  1.05  1.27  0.56 -0.07 -0.15 -0.21 -0.05]
 [ 0.16  0.58  0.38  0.42  0.28  0.06  0.13  0.19  0.22]
 [ 0.16  0.58  0.38  0.42  0.28  0.06  0.13  0.19  0.22]
 [ 0.22  0.55  0.51  0.63  0.24 -0.07 -0.14 -0.2  -0.11]
 [ 0.1   0.53  0.23  0.21  0.27  0.14  0.31  0.44  0.42]
 [-0.06  0.23 -0.14 -0.27  0.14  0.24  0.55  0.77  0.66]
 [-0.06  0.34 -0.15 -0.3   0.2   0.31  0.69  0.98  0.85]
 [-0.04  0.25 -0.1  -0.21  0.15  0.22  0.5   0.71  0.62]]


 Corrélations obtenues avec les matrices ALS :
[[ 1.    0.91  1.    1.    0.84 -0.86 -0.85 -0.85 -0.81]
 [ 0.91  1.    0.91  0.88  0.99 -0.57 -0.56 -0.56 -0.5 ]
 [ 1.    0.91  1.    1.    0.84 -0.86 -0.85 -0.85 -0.81]
 [ 1.    0.88  1.    1.    0.81 -0

In [34]:
P3, Q3 = ALS(mat, 3)
print("Produit des matrices résultantes :")
print(np.round(P3 @ Q3 ,2))
print('\n\n',"Corrélations obtenues avec les matrices ALS :")
print(np.round(np.corrcoef(P3 @ Q3, rowvar = False), 2))
print('\n',"Corrélations obtenues avec la démo SVD de Landauer :")
print(land_svd3)

Number of iterations : 14
Produit des matrices résultantes :
[[ 0.24  0.06  0.52  0.86 -0.17  0.01  0.02  0.01 -0.04]
 [ 0.18  0.21  0.39  0.58  0.   -0.   -0.01 -0.02 -0.02]
 [ 0.11  0.7   0.28  0.19  0.43 -0.01 -0.01 -0.01  0.09]
 [ 0.17  1.24  0.44  0.24  0.79 -0.04 -0.07 -0.08  0.12]
 [ 0.54  0.81  1.23  1.75  0.13  0.01  0.01  0.01  0.02]
 [ 0.05  1.08  0.17 -0.15  0.78 -0.04 -0.06 -0.06  0.14]
 [ 0.05  1.08  0.17 -0.15  0.78 -0.04 -0.06 -0.06  0.14]
 [ 0.3   0.16  0.67  1.07 -0.15  0.01  0.01  0.   -0.05]
 [ 0.05  0.74  0.14 -0.03  0.48  0.1   0.23  0.34  0.39]
 [-0.   -0.04 -0.03  0.04 -0.13  0.29  0.65  0.9   0.71]
 [-0.01  0.07 -0.04 -0.   -0.06  0.36  0.8   1.11  0.89]
 [-0.01  0.09 -0.03 -0.02 -0.02  0.25  0.57  0.79  0.64]]


 Corrélations obtenues avec les matrices ALS :
[[ 1.    0.13  1.    0.97 -0.19 -0.49 -0.53 -0.54 -0.67]
 [ 0.13  1.    0.21 -0.14  0.95 -0.67 -0.63 -0.62 -0.4 ]
 [ 1.    0.21  1.    0.94 -0.11 -0.55 -0.58 -0.6  -0.71]
 [ 0.97 -0.14  0.94  1.   -0.44 -0

Les résultats obtenus avec les matrices déterminées par ALS sont quasiment identiques à ceux obtenus par SVD. A 2 dimensions on retrouve une corrélation parfaite entre les articles de la convention d'algèbre linéaire et assez bonne pour la plupart des cas de la convention d'IHM mais assez mauvais pour les articles 2 et 5. De même, les résultats sont un peu moins bon avec 3 dimensions comme avec SVD car le problème n'a que deux classes donc le 3 axes n'est pas intéressant.

#2. Sources des meilleurs résultats  
 

*   Le premier point est que dans le TP on utilise 100% des données pour l'entraînement donc en utilise relativement plus pour donner une prédiction plus précise pour la valeur testée.
*   Le second point est qu'il existe un biais d'évaluation car on teste sur des données utilisées pour l'entraînement. Notamment on retrouve des informations de la matrice de départ via l'inclusion de la moyenne dans la valeur prédite. Au contraire dans l'article, on effectue une validation croisée qui permet d'évaluer la performance sur des données qui ont été exclues lors de l'entraînement et donc qui ne sont pas corrélées avec les valeurs prédites.






#3. Utilisation du temps

Dans une approche par factorisation de matrice on peut définir des biais qui varient en fonction du temps pour la prédiction du vote de l'utilisateur u pour l'item i par rapport à la moyenne des votes μ : 

$$ \hat{r}_{ui}(t) = μ + b_i(t) + b_u(t) + q^T_ip_u(t) $$

$ b_i(t) $ représente le biais d'un item, son écart de valeur par rapport à la moyenne, il est par nature assez fixe et peut varier autour de sa moyenne selon la période (comme la saison dans l'année) :

$$ b_i(t) = b_i + b_{i,period}(t) $$

$ b_u(t) $ représente le biais d'un utilisateur et on pourrait le faire varier dans le temps selon l'éloignement par rapport à la date moyenne de vote ($t_u$) :

$$ b_u (t) = b_u + α_u · dev_u(t) $$

$$ dev_u(t) = sign(t − t_u) · |t − t_u|^β $$

Enfin, les matrices P et Q n'apprenent que les variations propres à chaque utilisateur et item par rapport à ces moyennes. On peut aussi modéliser dans la matrice P des variations linéaires de l'utilisateur par rapport à sa propre moyenne selon les jours qui passent pour chaque item spécifiquement qui représentera plus son changement de goûts :

$$ p_{uk}(t) = p_{uk} + α_{uk} · dev_u(t) + p_{uk,t}\ \ \ \ \ \ \ \ k = 1,...,f $$

[[Y. Koren, 2009]](https://dl.acm.org/doi/pdf/10.1145/1557019.1557072?casa_token=98GiLBY9w8UAAAAA:xddo0BpDfATzQsK1TY6SgAPo3A3NZPZ43TZnzGhuFdY3qhKuZK_oInbTfcqHQBz9F5H-63B1jq8p)

In [36]:
!jupyter nbconvert --to html atelier1.ipynb

[NbConvertApp] Converting notebook atelier1.ipynb to html
[NbConvertApp] Writing 300815 bytes to atelier1.html
